spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/scraper-news
    username: root
    password: r00t

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate.jdbc.batch_size: 50