package com.news.voicenews.enums;

public enum CrawlerStatus {
    IN_CRAWLING_NEWS_PROGRESS,
    NEWS_CRAWLER_SUCCESS,
    NEWS_CRAWLER_FAILED,
    IN_RANKER_PROGRESS,
    RANKER_SUCCESS,
    RANKER_FAILED,
    IN_CRAWLING_AUDIO_PROGRESS,
    AUDIO_CRAWLING_SUCCESS,
    AUDIO_CRAWLING_FAILED,
    FINISHED,
    FAILED
}
